/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Car;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author aelinadas
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private Car car;
    public ViewJPanel(Car car) {
        initComponents();
        this.car = car;
        DisplayCar(car);
    }

    
    private void DisplayCar(Car car){
        String carName = car.getName();
        nameText.setText(carName);
        String carAvail_num = car.getAvail_num();
        availTxt.setText(carAvail_num);
        String carColor = car.getColor();
        colorTxt.setText(carColor);
        String carDesc = car.getDescription();
        descTxt.setText(carDesc);
        String carDim = car.getDimensions();
        dmTxt.setText(carDim);
        String carDisplay = car.getDisplay();
        displayTxt.setText(carDisplay);
        String carDoor = car.getDoor();
        doorTxt.setText(carDoor);
        String carHP = car.getHorsePower();
        hpTxt.setText(carHP);
        String carLight = car.getLights();
        lightTxt.setText(carLight);
        String carMirror = car.getMirrors();
        mirrorTxt.setText(carMirror);
        String carModel = car.getModel();
        modelTxt.setText(carModel);
        String carPrice = car.getPrice();
        priceTxt.setText(carPrice);
        String carSeat = car.getSeat_type();
        seatTxt.setText(carSeat);
        String carSerial = car.getSerial_no();
        serialTxt.setText(carSerial);
        String carwheel = car.getWheel_arm();
        wheelTxt.setText(carwheel);
        if(car.getBtnUpload()!= null){
        JLabel label = new JLabel();
        label.setBounds(500, 150, 500, 500);
        add(label);
        Image icon = new ImageIcon(car.getBtnUpload()).getImage();
        Image newIcon = icon.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon newIconImage = new ImageIcon(newIcon);
        label.setIcon(newIconImage);
      
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        create = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        serial_no = new javax.swing.JLabel();
        dimensions = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        avail_num = new javax.swing.JLabel();
        seat_type = new javax.swing.JLabel();
        lights = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        horsePower = new javax.swing.JLabel();
        door = new javax.swing.JLabel();
        wheel_arm = new javax.swing.JLabel();
        mirrors = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        modelTxt = new javax.swing.JTextField();
        colorTxt = new javax.swing.JTextField();
        serialTxt = new javax.swing.JTextField();
        dmTxt = new javax.swing.JTextField();
        descTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        availTxt = new javax.swing.JTextField();
        seatTxt = new javax.swing.JTextField();
        lightTxt = new javax.swing.JTextField();
        displayTxt = new javax.swing.JTextField();
        hpTxt = new javax.swing.JTextField();
        doorTxt = new javax.swing.JTextField();
        wheelTxt = new javax.swing.JTextField();
        mirrorTxt = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        create.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        create.setText("View");

        name.setText("Name:");

        model.setText("Model:");

        color.setText("Color:");

        serial_no.setText("Serial No:");

        dimensions.setText("Dimensions:");

        description.setText("Description:");

        price.setText("Price:");

        avail_num.setText("Available No:");

        seat_type.setText("Seat Type:");

        lights.setText("Lights:");

        display.setText("Display:");

        horsePower.setText("Horse Power:");

        door.setText("Wheel Arm:");

        wheel_arm.setText("Door:");

        mirrors.setText("Mirrors:");

        serialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialTxtActionPerformed(evt);
            }
        });

        dmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmTxtActionPerformed(evt);
            }
        });

        availTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availTxtActionPerformed(evt);
            }
        });

        lightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightTxtActionPerformed(evt);
            }
        });

        displayTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTxtActionPerformed(evt);
            }
        });

        mirrorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirrorTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mirrors)
                    .addComponent(serial_no)
                    .addComponent(color)
                    .addComponent(dimensions)
                    .addComponent(description)
                    .addComponent(price)
                    .addComponent(avail_num)
                    .addComponent(seat_type)
                    .addComponent(lights)
                    .addComponent(display)
                    .addComponent(horsePower)
                    .addComponent(wheel_arm)
                    .addComponent(door)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(name)
                        .addComponent(model)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(wheelTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(doorTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hpTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(displayTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lightTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seatTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(availTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(priceTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(descTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dmTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serialTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(colorTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(modelTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(mirrorTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(create)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(create)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serial_no)
                    .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimensions, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description)
                    .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avail_num)
                    .addComponent(availTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat_type)
                    .addComponent(seatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lights)
                    .addComponent(lightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display)
                    .addComponent(displayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horsePower)
                    .addComponent(hpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wheel_arm)
                    .addComponent(doorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(door)
                    .addComponent(wheelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mirrors)
                    .addComponent(mirrorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialTxtActionPerformed

    private void dmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dmTxtActionPerformed

    private void availTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availTxtActionPerformed

    private void lightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightTxtActionPerformed

    private void displayTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayTxtActionPerformed

    private void mirrorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirrorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mirrorTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availTxt;
    private javax.swing.JLabel avail_num;
    private javax.swing.JLabel color;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JLabel create;
    private javax.swing.JTextField descTxt;
    private javax.swing.JLabel description;
    private javax.swing.JLabel dimensions;
    private javax.swing.JLabel display;
    private javax.swing.JTextField displayTxt;
    private javax.swing.JTextField dmTxt;
    private javax.swing.JLabel door;
    private javax.swing.JTextField doorTxt;
    private javax.swing.JLabel horsePower;
    private javax.swing.JTextField hpTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lightTxt;
    private javax.swing.JLabel lights;
    private javax.swing.JTextField mirrorTxt;
    private javax.swing.JLabel mirrors;
    private javax.swing.JLabel model;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField seatTxt;
    private javax.swing.JLabel seat_type;
    private javax.swing.JTextField serialTxt;
    private javax.swing.JLabel serial_no;
    private javax.swing.JTextField wheelTxt;
    private javax.swing.JLabel wheel_arm;
    // End of variables declaration//GEN-END:variables
}
