/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.UberDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author aelinadas
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    private UberDirectory uberDirectory;
    private JPanel userJPanelController;
    SearchJPanel(JPanel userJPanelController, UberDirectory uberDirectory) {
        initComponents();
        this.uberDirectory = uberDirectory;
        this.userJPanelController = userJPanelController;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAvailable = new javax.swing.JButton();
        btnCurrentlyAvail = new javax.swing.JButton();
        btnCarName = new javax.swing.JButton();
        btnManufacture = new javax.swing.JButton();
        btnSeats = new javax.swing.JButton();
        btnSerialNo = new javax.swing.JButton();
        btnModelNo = new javax.swing.JButton();
        btnCarList = new javax.swing.JButton();
        btnFleetCatalog = new javax.swing.JButton();
        btnCarsCity = new javax.swing.JButton();
        btnExpiredCertificate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        btnAvailable.setText("First Available Car");
        btnAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableActionPerformed(evt);
            }
        });

        btnCurrentlyAvail.setText("Currently Available Cars");
        btnCurrentlyAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentlyAvailActionPerformed(evt);
            }
        });

        btnCarName.setText("Car List by Name");
        btnCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarNameActionPerformed(evt);
            }
        });

        btnManufacture.setText("Car List by Manufacture Year ");
        btnManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufactureActionPerformed(evt);
            }
        });

        btnSeats.setText("Car List with Min Seats");
        btnSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsActionPerformed(evt);
            }
        });

        btnSerialNo.setText("Car List by Serial Number");
        btnSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNoActionPerformed(evt);
            }
        });

        btnModelNo.setText("Car List by Model Number");
        btnModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNoActionPerformed(evt);
            }
        });

        btnCarList.setText("Cars listed in Uber");
        btnCarList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarListActionPerformed(evt);
            }
        });

        btnFleetCatalog.setText("Fleet Catalog Updated");
        btnFleetCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFleetCatalogActionPerformed(evt);
            }
        });

        btnCarsCity.setText("Cars available in a City");
        btnCarsCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarsCityActionPerformed(evt);
            }
        });

        btnExpiredCertificate.setText("Car List with Expired Certificate");
        btnExpiredCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredCertificateActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCurrentlyAvail)
                            .addComponent(btnCarName)
                            .addComponent(btnManufacture)
                            .addComponent(btnSeats)
                            .addComponent(btnSerialNo)
                            .addComponent(btnModelNo)
                            .addComponent(btnCarList)))
                    .addComponent(btnFleetCatalog)
                    .addComponent(btnCarsCity)
                    .addComponent(btnExpiredCertificate)
                    .addComponent(btnBack))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAvailable, btnBack, btnCarList, btnCarName, btnCarsCity, btnCurrentlyAvail, btnExpiredCertificate, btnFleetCatalog, btnManufacture, btnModelNo, btnSeats, btnSerialNo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCurrentlyAvail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManufacture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSerialNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModelNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFleetCatalog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarsCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExpiredCertificate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpiredCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredCertificateActionPerformed
        // TODO add your handling code here:
        MaintenanceCertListJPanel maintenanceCertListJPanel = new MaintenanceCertListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("MaintenanceCertListJPanel", maintenanceCertListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnExpiredCertificateActionPerformed

    private void btnCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarNameActionPerformed
        // TODO add your handling code here:
        CarNameListJPanel carNameListJPanel = new CarNameListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("CarNameListJPanel", carNameListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnCarNameActionPerformed

    private void btnManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufactureActionPerformed
        // TODO add your handling code here:
        ManufactureYearListJPanel manufactureYearListJPanel = new ManufactureYearListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("ManufactureYearListJPanel", manufactureYearListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnManufactureActionPerformed

    private void btnSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNoActionPerformed
        // TODO add your handling code here:
        SerialNumberListJPanel serialNumberListJPanel = new SerialNumberListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("SerialNumberListJPanel", serialNumberListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnSerialNoActionPerformed

    private void btnModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNoActionPerformed
        // TODO add your handling code here:
        ModelNumberListJPanel modelNumberListJPanel = new ModelNumberListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("ModelNumberListJPanel", modelNumberListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnModelNoActionPerformed

    private void btnCarListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarListActionPerformed
        // TODO add your handling code here:
       CarManufacturersUberJPanel carManufacturersUberJPanel = new CarManufacturersUberJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("CarManufacturersUberJPanel", carManufacturersUberJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnCarListActionPerformed

    private void btnCarsCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarsCityActionPerformed
        // TODO add your handling code here:
        CityBasedListJPanel cityBasedListJPanel = new CityBasedListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("CityBasedListJPanel", cityBasedListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnCarsCityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userJPanelController.remove(this);
        CardLayout layout = (CardLayout)userJPanelController.getLayout();
        layout.previous(userJPanelController);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsActionPerformed
        // TODO add your handling code here:
        NumberOfSeatListJPanel numberOfSeatListJPanel = new NumberOfSeatListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("NumberOfSeatListJPanel", numberOfSeatListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnSeatsActionPerformed

    private void btnAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableActionPerformed
        // TODO add your handling code here:
        FirstAvailableCarJPanel firstAvailableCarJPanel = new FirstAvailableCarJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("FirstAvailableCarJPanel", firstAvailableCarJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnAvailableActionPerformed

    private void btnCurrentlyAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentlyAvailActionPerformed
        // TODO add your handling code here:
        AvailableUnavailableCarListJPanel availableUnavailableCarListJPanel = new AvailableUnavailableCarListJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("AvailableUnavailableCarListJPanel", availableUnavailableCarListJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnCurrentlyAvailActionPerformed

    private void btnFleetCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFleetCatalogActionPerformed
        // TODO add your handling code here:\
        FleetLastUpdatedJPanel fleetLastUpdatedJPanel = new FleetLastUpdatedJPanel(userJPanelController, uberDirectory);
        userJPanelController.add("FleetLastUpdatedJPanel", fleetLastUpdatedJPanel);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnFleetCatalogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCarList;
    private javax.swing.JButton btnCarName;
    private javax.swing.JButton btnCarsCity;
    private javax.swing.JButton btnCurrentlyAvail;
    private javax.swing.JButton btnExpiredCertificate;
    private javax.swing.JButton btnFleetCatalog;
    private javax.swing.JButton btnManufacture;
    private javax.swing.JButton btnModelNo;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnSerialNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
