 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Uber;
import business.UberDirectory;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aelinadas
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private UberDirectory uberDirectory;
    private JPanel userJPanelController;
   CreateJPanel(JPanel userJPanelController, UberDirectory uberDirectory) {
       initComponents();
       this.uberDirectory = uberDirectory;
       this.userJPanelController = userJPanelController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateField = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblSerialNo = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        lblYearOfManufacture = new javax.swing.JLabel();
        txtYearOfManufacture = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblCheckAvailability = new javax.swing.JLabel();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        chkAvail = new javax.swing.JCheckBox();
        chkMaintain = new javax.swing.JCheckBox();

        lblCreateField.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblCreateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblCreateField.setText("CREATE CAR SPECIFICATIONS");
        lblCreateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCreateFieldActionPerformed(evt);
            }
        });

        lblName.setText("Car Name:");

        txtCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNameActionPerformed(evt);
            }
        });
        txtCarName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarNameKeyTyped(evt);
            }
        });

        lblModel.setText("Model Number:");

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });
        txtModelNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModelNumberKeyTyped(evt);
            }
        });

        lblSerialNo.setText("Serial Number:");

        txtSerialNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialNumberKeyTyped(evt);
            }
        });

        lblSeats.setText("Seats:");

        txtSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeatsKeyTyped(evt);
            }
        });

        lblYearOfManufacture.setText("Year of Manufacture:");

        txtYearOfManufacture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearOfManufactureKeyTyped(evt);
            }
        });

        lblCity.setText("City Name:");

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCityKeyTyped(evt);
            }
        });

        lblCheckAvailability.setText("Check Availability:");

        lblMaintenanceCertificate.setText("Expired Maintenance Certificate:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        chkAvail.setText("Available");
        chkAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailActionPerformed(evt);
            }
        });

        chkMaintain.setText("Yes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblCreateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSerialNo)
                                    .addComponent(lblModel)
                                    .addComponent(lblSeats)
                                    .addComponent(lblYearOfManufacture))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCheckAvailability)
                            .addComponent(lblCity)
                            .addComponent(lblMaintenanceCertificate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkMaintain)
                            .addComponent(chkAvail))))
                .addContainerGap(413, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(btnCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnCreate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCreateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNo)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearOfManufacture)
                    .addComponent(txtYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckAvailability)
                    .addComponent(chkAvail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintenanceCertificate)
                    .addComponent(chkMaintain))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate)
                    .addComponent(btnBack))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnCreate});

    }// </editor-fold>//GEN-END:initComponents

    private void lblCreateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCreateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCreateFieldActionPerformed

    private void txtCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(txtCarName.getText().equals("") || txtCity.getText().equals("") || txtModelNumber.getText().equals("") || txtSeats.getText().equals("") || txtSerialNumber.getText().equals("") || txtYearOfManufacture.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter some inputs!!");
        }else{
            Uber uber = uberDirectory.addCar();
            uber.setCarName(txtCarName.getText());
            uber.setCity(txtCity.getText());
            uber.setModelNumber(txtModelNumber.getText());
            uber.setSerialNumber(txtSerialNumber.getText());
            uber.setSeats(Integer.parseInt(txtSeats.getText()));
            uber.setManufactureYear(Integer.parseInt(txtYearOfManufacture.getText()));
            uber.setMaintenanceCertificate(chkMaintain.isSelected());
            uber.setAvailability(chkAvail.isSelected());
            JOptionPane.showMessageDialog(null, "Successfully added Car specifications");
            txtCarName.setText("");
            txtCity.setText("");
            txtModelNumber.setText("");
            txtSerialNumber.setText("");
            txtYearOfManufacture.setText("");
            txtSeats.setText("");
            chkAvail.setSelected(false);
            chkMaintain.setSelected(false);   
        }
           
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userJPanelController.remove(this);
        CardLayout cardLayout = (CardLayout)userJPanelController.getLayout();
        cardLayout.next(userJPanelController);
    }//GEN-LAST:event_btnBackActionPerformed

    private void chkAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvailActionPerformed

    private void txtCarNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarNameKeyTyped
        // TODO add your handling code here:
        int chk=evt.getKeyCode();
        char ch = evt.getKeyChar();
        if(!Character.isLetter(ch) && (chk!= KeyEvent.VK_BACK_SPACE) && !Character.isWhitespace(ch)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCarNameKeyTyped

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void txtModelNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelNumberKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(!Character.isLetter(ch) && (ch == KeyEvent.VK_BACK_SPACE) && !Character.isWhitespace(ch)){
            evt.consume();
        }
    }//GEN-LAST:event_txtModelNumberKeyTyped

    private void txtSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatsKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        int num = evt.getKeyCode();
        if(!Character.isDigit(ch) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtSeatsKeyTyped

    private void txtYearOfManufactureKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearOfManufactureKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        int num = evt.getKeyCode();
        if(!Character.isDigit(ch) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtYearOfManufactureKeyTyped

    private void txtCityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyTyped
        // TODO add your handling code here:
        int chk=evt.getKeyCode();
        char ch = evt.getKeyChar();
        if(!Character.isLetter(ch) && (chk!= KeyEvent.VK_BACK_SPACE) && !Character.isWhitespace(ch)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCityKeyTyped

    private void txtSerialNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumberKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(!Character.isLetter(ch) && (ch == KeyEvent.VK_BACK_SPACE) && !Character.isWhitespace(ch)){
            evt.consume();
        }
    }//GEN-LAST:event_txtSerialNumberKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JCheckBox chkAvail;
    private javax.swing.JCheckBox chkMaintain;
    private javax.swing.JLabel lblCheckAvailability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JTextField lblCreateField;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblYearOfManufacture;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtYearOfManufacture;
    // End of variables declaration//GEN-END:variables
}
