/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Uber;
import business.UberDirectory;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aelinadas
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel userJPanelController;
    private Uber uber;
    private UberDirectory uberDirectory;
    ViewJPanel(JPanel userJPanelController, Uber uber, UberDirectory uberDirectory) {
        initComponents();
        this.userJPanelController = userJPanelController;
        this.uber = uber;
        this.uberDirectory = uberDirectory;
        populateDetails();
    }

    private void populateDetails(){
        txtCarName.setText(uber.getCarName());
        txtCity.setText(uber.getCity());
        txtModelNumber.setText(uber.getModelNumber());
        txtSerialNumber.setText(uber.getSerialNumber());
        txtYearOfManufacture.setText(Integer.toString(uber.getManufactureYear()));
        txtSeats.setText(Integer.toString(uber.getSeats()));
        chkAvail.setSelected(uber.getAvailability());
        chkMaintain.setSelected(uber.getMaintenanceCertificate());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblCreateField = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtCarName = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        lblSerialNo = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        lblYearOfManufacture = new javax.swing.JLabel();
        txtYearOfManufacture = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblCheckAvailability = new javax.swing.JLabel();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        chkMaintain = new javax.swing.JCheckBox();
        chkAvail = new javax.swing.JCheckBox();

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCreateField.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblCreateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblCreateField.setText("VIEW CAR SPECIFICATIONS");
        lblCreateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCreateFieldActionPerformed(evt);
            }
        });

        lblName.setText("Car Name:");

        txtCarName.setEnabled(false);
        txtCarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarNameActionPerformed(evt);
            }
        });
        txtCarName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarNameKeyTyped(evt);
            }
        });

        lblModel.setText("Model Number:");

        txtModelNumber.setEnabled(false);
        txtModelNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModelNumberKeyTyped(evt);
            }
        });

        lblSerialNo.setText("Serial Number:");

        txtSerialNumber.setEnabled(false);
        txtSerialNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialNumberKeyTyped(evt);
            }
        });

        lblSeats.setText("Number of Seats:");

        txtSeats.setEnabled(false);
        txtSeats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeatsKeyTyped(evt);
            }
        });

        lblYearOfManufacture.setText("Year of Manufacture:");

        txtYearOfManufacture.setEnabled(false);
        txtYearOfManufacture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearOfManufactureKeyTyped(evt);
            }
        });

        lblCity.setText("City Name:");

        txtCity.setEnabled(false);
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCityKeyTyped(evt);
            }
        });

        lblCheckAvailability.setText("Check Availability:");

        lblMaintenanceCertificate.setText("Expired Maintenance Certificate:");

        chkMaintain.setText("Yes");
        chkMaintain.setEnabled(false);

        chkAvail.setText("if available");
        chkAvail.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblYearOfManufacture)
                                .addComponent(lblCity)
                                .addComponent(lblCheckAvailability)
                                .addComponent(lblMaintenanceCertificate)
                                .addComponent(lblName)
                                .addComponent(lblSeats)
                                .addComponent(lblSerialNo)
                                .addComponent(lblModel))
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(chkAvail)
                                .addComponent(chkMaintain))
                            .addGap(291, 291, 291))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCreateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(313, 313, 313))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnSave, btnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCreateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNo)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearOfManufacture)
                    .addComponent(txtYearOfManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckAvailability)
                    .addComponent(chkAvail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintenanceCertificate)
                    .addComponent(chkMaintain))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCreateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCreateFieldActionPerformed

    private void txtCarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userJPanelController.remove(this);
        CardLayout layout = (CardLayout)userJPanelController.getLayout();
        layout.previous(userJPanelController);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        uber.setCarName(txtCarName.getText());
        uber.setModelNumber(txtModelNumber.getText());
        uber.setCity(txtCity.getText());
        uber.setSerialNumber(txtSerialNumber.getText());
        uber.setSeats(Integer.parseInt(txtSeats.getText()));
        uber.setManufactureYear(Integer.parseInt(txtYearOfManufacture.getText()));
        uber.setAvailability(chkAvail.isSelected());
        uber.setMaintenanceCertificate(chkMaintain.isSelected());
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        
        DateFormat date = new SimpleDateFormat("MM/DD/YYYY HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        uberDirectory.setLastModified(date.format(cal.getTime()));
        
        JOptionPane.showMessageDialog(null, "Car updated successfully!!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtCarName.setEnabled(true);
         txtCity.setEnabled(true);
         txtModelNumber.setEnabled(true);
         txtSeats.setEnabled(true);
         txtSerialNumber.setEnabled(true);
         txtYearOfManufacture.setEnabled(true);
         chkAvail.setEnabled(true);
         chkAvail.setVisible(true);
         chkMaintain.setEnabled(true);
         
         btnSave.setEnabled(true);
         btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtCarNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarNameKeyTyped
        // TODO add your handling code here:
        int chk=evt.getKeyCode();
        char ch = evt.getKeyChar();
        if(!Character.isLetter(ch) && (chk!= KeyEvent.VK_BACK_SPACE) && !Character.isWhitespace(ch)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCarNameKeyTyped

    private void txtModelNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelNumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberKeyTyped

    private void txtSerialNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberKeyTyped

    private void txtSeatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatsKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        int num = evt.getKeyCode();
        if(!Character.isDigit(ch) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtSeatsKeyTyped

    private void txtYearOfManufactureKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearOfManufactureKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        int num = evt.getKeyCode();
        if(!Character.isDigit(ch) || (ch == KeyEvent.VK_BACK_SPACE) || (ch == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtYearOfManufactureKeyTyped

    private void txtCityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyTyped
        // TODO add your handling code here:
        int chk=evt.getKeyCode();
        char ch = evt.getKeyChar();
        if(!Character.isLetter(ch) && (chk!= KeyEvent.VK_BACK_SPACE) && !Character.isWhitespace(ch)){
            evt.consume();
        }
    }//GEN-LAST:event_txtCityKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkAvail;
    private javax.swing.JCheckBox chkMaintain;
    private javax.swing.JLabel lblCheckAvailability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JTextField lblCreateField;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblYearOfManufacture;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtYearOfManufacture;
    // End of variables declaration//GEN-END:variables
}
